### ISSUE TITLE
[overhaul-2122] Faltan textos de instrucciones en la interfaz del profesor

### ISSUE THREAD

**Issue by claudio-alvarez** [EthicApp-Development/ethicapp-main#117]
# Descripción del error/bug
De acuerdo a la documentación de diseño de la interfaz del profesor, las vistas del profesor comúnmente tienen un párrafo de instrucciones debajo del título. En la mayoría de las vistas, estas instrucciones faltan.

# Detalles
## ¿Cuándo ocurrió?
Esto ocurre en el último commit ([3525ff9](https://github.com/EthicApp-Development/ethicapp-main/commit/3525ff91f7b893b2580958c0e1a8070cc717cb11)) en la rama overhaul-2122 al momento de levantar este issue.

## ¿En qué dispositivo fue?
En mi Mac.

## ¿En qué explorador web ocurrió?
En Google Chrome.

## ¿Cómo reproducir el error?

Acceder a "Diseños de Actividades". Vemos que hay una comparación poco feliz entre el diseño del mockup y el resultado implementado en la interfaz:

Documento de diseño:
<img width="734" alt="Screen Shot 2023-05-09 at 16 04 13" src="https://github.com/EthicApp-Development/ethicapp-main/assets/752908/02dfc78d-6a9f-414d-a854-7c62049be304">

Interfaz actual:
<img width="833" alt="Screen Shot 2023-05-09 at 16 03 49" src="https://github.com/EthicApp-Development/ethicapp-main/assets/752908/5d17d963-898b-4a42-a965-9dc728247793">

Acceder a vista de "Actividades".

Documento de diseño:

<img width="495" alt="Screen Shot 2023-05-09 at 16 05 12" src="https://github.com/EthicApp-Development/ethicapp-main/assets/752908/66f4da45-5130-475e-b7bc-bb5b566fb3e4">

Interfaz actual:

<img width="838" alt="Screen Shot 2023-05-09 at 16 05 26" src="https://github.com/EthicApp-Development/ethicapp-main/assets/752908/741bdf25-45db-4bed-b932-9191f09c59de">

**Comment by mabarraza** [comment]
Cerrado en PR #173
