### ISSUE TITLE
[ethicapp-v2] Renombrar PRs e issues para reflejar cambio de nombre de rama EthicApp 2.0

### ISSUE THREAD

**Issue by ifgarces** [EthicApp-Development/ethicapp-main#152]
# Descripción general
Ya que la rama `overhaul-2122` fue renombrada a `ethicapp-v2`, es necesario renombrar las issues y PRs (al menos las abiertas) tediosamente, reemplazando "`[overhaul-2122]`" por el nuevo nombre de la rama.

# ¿Por qué es necesario?
Para que haya consistencia del formato de las issues y PRs.

**Comment by mabarraza** [comment]
El renombramiento de PRs e issues activos ha sido realizado, así como también se actualizaron algunos issues más antiguos y se cerraron aquellos que ya no aplicaban
