### ISSUE TITLE
[ethicapp-v2] Falla apertura de websocket en interfaz del docente en vista home

### ISSUE THREAD

**Issue by claudio-alvarez** [EthicApp-Development/ethicapp-main#161]
# Descripción del error/bug
Cuando se accede a la vista home del docente en ambiente de staging, falla la creación de _websocket_ con el backend. Al no haber _websocket_, fallan las funciones de monitoreo de estado de actividades, y posiblemente otras.

<img width="1013" alt="Screenshot 2023-07-06 at 17 29 41" src="https://github.com/EthicApp-Development/ethicapp-main/assets/752908/749c4eae-3bde-470c-86c1-82e399d6c538">

**Se debe verificar si se trata de un problema de configuración en ambiente de staging (nginx?), o si también ocurre en ambiente de desarrollo.**

# Detalles
## ¿Cuándo ocurrió?

6 de julio de 2023, 17:00

## ¿En qué dispositivo fue?

MBP del BDFL

## ¿En qué explorador web ocurrió?

Chrome para macOS Version 114.0.5735.198 (Official Build) (arm64)

## ¿Cómo reproducir el error?

Ingresar a ambiente de staging en https://alpha.ethicapp.info

**Comment by mabarraza** [comment]
Resuelto en PR# #183
