### ISSUE TITLE
[ethicapp-v2] Usar iconografía inspirada en MIT Scratch para selección de idioma

### ISSUE THREAD

**Issue by claudio-alvarez** [EthicApp-Development/ethicapp-main#184]
# Descripción general
Actualmente tenemos un botón en el topbar que permite hacer cambio de idioma. Daría mejor impresión y experiencia usar un ícono similar al que incorpora Scratch para desplegar una lista de los idiomas soportados.

# ¿Por qué es necesario?
Para mejorar la calidad visual y la experiencia del usuario con la aplicación.

# Información de respaldo
https://github.com/EthicApp-Development/ethicapp-main/assets/752908/95536779-a620-4208-8d2e-5757f193a932

**Comment by mabarraza** [comment]
Resuelto en PR #190
