### ISSUE TITLE
[ethicapp-v2] Selección de modo anónimo por default cuando se configura fase grupal

### ISSUE THREAD

**Issue by claudio-alvarez** [EthicApp-Development/ethicapp-main#188]
# Descripción general
Actualmente cuando se crea una fase grupal en un diseño de actividad, se asume por default que la interacción no es anónima, y se esconde esta decisión al diseñador (hay que presionar un link para ver opciones avanzadas). La **interacción en una fase grupal debe ser anónima por default**.

# ¿Por qué es necesario?
Esto inconveniente que la interacción no anónima sea default, pues en la discusión de dilemas éticos generalmente la discusión es anónima, para evitar inhibiciones de los colaboradores.

# Información de respaldo
<img width="641" alt="Screenshot 2023-08-29 at 11 17 06" src="https://github.com/EthicApp-Development/ethicapp-main/assets/752908/0dc00af8-8b1a-4ac0-8781-f7d5461e4968">

**Comment by mabarraza** [comment]
Resuelto en PR #190
