### ISSUE TITLE
[ethicapp-v2] No aparece el código de sesión al iniciar una actividad a partir de un diseño escogido

### ISSUE THREAD

**Issue by claudio-alvarez** [EthicApp-Development/ethicapp-main#189]
# Descripción del error/bug
Cuando se crea una nueva actividad a partir de un diseño escogido, el comportamiento de la interfaz es extraño. Pareciera aparecer abajo en la página una caja negra, y luego hay una redirección a la vista de monitoreo/dashboard, pero sin que aparezca el código de sesión. El código de sesión aparece cuando se refresca la página.

# Detalles
## ¿Cuándo ocurrió?
Al realizar una prueba en staging (alpha.ethicapp.info) el 29 de agosto de 2023 a las 11:20 hrs.

## ¿En qué dispositivo fue?
Mac Mini del BFDL

## ¿En qué explorador web ocurrió?
Chrome Version 116.0.5845.110 (Official Build) (x86_64)

## ¿Cómo reproducir el error?

Seguir los pasos mostrados en el siguiente vídeo, en el ambiente de staging (alpha.ethicapp.info):

https://github.com/EthicApp-Development/ethicapp-main/assets/752908/4b2bbe0b-7a08-43f8-b139-d134f8af8ec4

## Detalles adicionales
Si bien se justifica una redirección entre la vista que permite instanciar el diseño (crear la actividad), y la vista de dashboard, es indeseable la caja negra que aparece en la primera vista, al pinchar en "lanzar actividad". Eliminemos esta caja, y demos al usuario un feedback temporal mientras ocurre la redirección. Puede ser un spinner pequeño (altura de 1em), acompañado por un mensaje que diga "Preparando dashboard para la actividad..." / "Preparing the activity dashboard...".

**Comment by mabarraza** [comment]
Resuelto en PR #190
