### ISSUE TITLE
[ethicapp-v2] Dominio de EthicApp en producción configurable en tiempo de instalación a través de task 

### ISSUE THREAD

**Issue by claudio-alvarez** [EthicApp-Development/ethicapp-main#198]
# Descripción general
Es necesario implementar un script/task para la instalación en producción que permita establecer el dominio en el cual opera la aplicación, y que dicho dominio quede guardado en la base de datos, en la tabla `institution`. 

Se debe incorporar a `INSTALL.md` la descripción de esta funcionalidad.

# ¿Cuándo se usaría?
Al instalar EthicApp en ambiente de producción, o al modificar el dominio de la aplicación. Esto permite que la información sobre el dominio bajo el cual opera la aplicación quede disponible para cuestiones como callbacks desde Google y otras APIs remotas. Casi todos los templates de correo que ha generado @William-CarterG requieren poder determinar el dominio de la aplicación en el código del backend. Además, más grave actualmente, la autenticación con Google no funciona porque una URL de callback en el backend está hardcodeada (!) con "localhost" 🤦🏻‍♂️, y esto es porque se ha omitido mantener esta información en la base de datos de la aplicación.

# Más información
Ver `ethicapp/backend/controllers/passport-setup.js`, y buscar `GoogleStrategy`, campo `callbackURL`.

**Comment by claudio-alvarez** [comment]
Se me ocurre que el task podría depender de un módulo que haga las operaciones de set (insert/update) y get (select) del campo domain desde la base de datos. Si existe el getter, entonces se hace más fácil resolver. Las funciones tendrían que ser:

```es6
getApplicationDomainName()
setApplicationDomainName(domain)
```

**Comment by claudio-alvarez** [comment]
@jigracia propone que el problema podría resolverse rápidamente si introducimos una variable de entorno a .env y utilizamos dicha variable en los controladores de la aplicación de backend. @jigracia, pienso que podríamos agregar al repositorio un archivo .env.example que podamos distribuir con la aplicación.

@vicentegana10, @mabarraza, podemos intentar la solución de usar variable de entorno. La variable de entorno tendría que ser ETHICAPP_DOMAIN_NAME.
Para la instalación en staging considerar:
ETHICAPP_DOMAIN_NAME=alpha.ethicapp.info

**Comment by mabarraza** [comment]
Perfecto lo veré y hablaré con @jigracia  y @vicentegana10
