### ISSUE TITLE
[master] Renombrar rama master a ethicapp-v1

### ISSUE THREAD

**Issue by claudio-alvarez** [EthicApp-Development/ethicapp-main#207]
# Descripción general
Actualmente tenemos el desarrollo distribuido en dos ramas. La rama master es para dar mantenimiento a la primera versión de ethicapp, y actualmente trabajamos en la rama ethicapp-v2.

Es necesario revertir el último merge a la rama master, en donde se le integró código de la rama ethicapp-v2. La idea es mantener ethicapp v1 en la rama master, por lo que su nombre tiene que cambiar a ethicapp-v1. Además, la rama default del repositorio debe ser ethicapp-v2.

Una vez que se establezca la rama ethicapp-v1 y se revierta la mezcla con código de ethicapp-v2, se debiera crear un tag en la rama ethicapp-v1 con HEAD, indicando que es la versión 1.0.0.

# ¿Por qué es necesario?
Para mantener consistencia de las dos ramas distintas del desarrollo, y mantener ethicapp-v1 aún disponible con fines de investigación.

**Comment by mabarraza** [comment]
@claudio-alvarez ya revertí el merge hecho en master, para cambiar el nombre y la rama default se requieren permisos de administrador así que asumo que usted puede editarlos, renombrar la rama es super directo como se muestra en [la documentación de github](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch) por otro lado para cambiar la rama default se pueden seguir los pasos de [aquí](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch)

**Comment by mabarraza** [comment]
Las ramas respectivas han sido renombradas y el release correspondiente a ethicapp-1.0 ya está listo,
