### ISSUE TITLE
[ethicapp-v2] Selección de idioma

### ISSUE THREAD

**Issue by claudio-alvarez** [EthicApp-Development/ethicapp-main#21]
Eliminemos los botones de toggle de selección de idioma y usemos el idioma con base a la API Navigator.language:
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/language

Podríamos hacer que al momento que ocurre el login, el idioma que reporta el browser quede en la sesión.

**Comment by mabarraza** [comment]
Entiendo que el tema de las traducciones se aborda de otra forma, si me lo puedes confirmar @claudio-alvarez  para ver si cierro el issue o lo dejo abierto

**Comment by claudio-alvarez** [comment]
Tanto en el frontend del alumno como en el profesor las traducciones están funcionando correctamente.
