### ISSUE TITLE
[ethicapp-v2] Actualizar secrets en ambiente de staging

### ISSUE THREAD

**Issue by claudio-alvarez** [EthicApp-Development/ethicapp-main#210]
# Descripción del error/bug
Necesitamos actualizar secrets en ambiente de staging, pues key de reCAPTCHA no es consistente con la más nueva generada.

# Detalles
## ¿Cuándo ocurrió?
El 4 de septiembre de 2023 a las 12:00 hrs.

## ¿En qué dispositivo fue?
Mac Mini del BFDL.

## ¿En qué explorador web ocurrió?
Chrome Version 116.0.5845.110 (Official Build) (x86_64)

## ¿Cómo reproducir el error?
Ingresar a página para creación de nueva cuenta en EthicApp en [alpha](https://alpha.ethicapp.info/register).

**Comment by mabarraza** [comment]
Al cambiar la secret key el, me encontré con un error de tipo de key:

![image](https://github.com/EthicApp-Development/ethicapp-main/assets/62113405/0690bd7c-e088-42d5-8abb-1db3bafc27e3)

Resulta que en el proyecto estamos usando reCAPTCHA V2, sin embargo las keys generadas para el servidor de staging fueron hechas para reCAPTCHA V3, las keys no son compatibles entre versiones generando así el error de la foto.
Para más información al respecto leer el [siguiente articulo.](https://formidableforms.com/knowledgebase/recaptcha/#kb-invalid-key-type:~:text=for%20further%20assistance.-,Invalid%20key%20type,-%23)

**Comment by mabarraza** [comment]
Solucionado en el PR #215
