### ISSUE TITLE
[ethicapp-v2] Mensajes en la interfaz del profesor defectuosos

### ISSUE THREAD

**Issue by claudio-alvarez** [EthicApp-Development/ethicapp-main#218]
# Descripción del error/bug
Hay varios mensajes en la interfaz del profesor que deben ser corregidos.

<img width="682" alt="Screenshot 2023-09-04 at 11 56 04" src="https://github.com/EthicApp-Development/ethicapp-main/assets/752908/3b798ed7-806a-49fe-883b-7543bab37930">

"Aquí puedes escoger un diseño de actividad para trabajar con tus estudiantes en EthicApp."
"Here you can choose an activity design to work with your students on EthicApp."

<img width="758" alt="Screenshot 2023-09-04 at 11 55 48" src="https://github.com/EthicApp-Development/ethicapp-main/assets/752908/3b2b2c72-0565-4ba6-b081-8f0a8057a8a7">

"Diseños de Actividad"
"Activity Designs"

# Detalles
## ¿Cuándo ocurrió?
5 de septiembre de 2023.

## ¿En qué dispositivo fue?
Mac Mini del BDFL.

## ¿En qué explorador web ocurrió?
Google Chrome Version 116.0.5845.140 (Official Build) (x86_64)

## ¿Cómo reproducir el error?
Acceder a las partes que se muestran en los pantallazos en el presente _issue_. Iremos agregando más mensajes defectuosos a este  _issue_ si los encontramos.

**Comment by mabarraza** [comment]
Resuelto en PR #216
