### ISSUE TITLE
[ethicapp-v2] Color de switch activo

### ISSUE THREAD

**Issue by claudio-alvarez** [EthicApp-Development/ethicapp-main#219]
# Descripción general
El verde en los switches actuales es un poco fuerte. Pienso que el verde #116329, más oscuro, funcionaría mejor.

Color original:
<img width="104" alt="Screenshot 2023-09-05 at 16 19 06" src="https://github.com/EthicApp-Development/ethicapp-main/assets/752908/58f6cb7b-5908-48e0-87a1-9b857d6b08b5">

Color propuesto:
<img width="99" alt="Screenshot 2023-09-05 at 16 19 56" src="https://github.com/EthicApp-Development/ethicapp-main/assets/752908/952f8ca5-0e7f-45db-9b25-82f0d87e6d23">

# ¿Por qué es necesario?
Para que no resalten los switches tan exageradamente.

**Comment by mabarraza** [comment]
Cerrado en PR #216
