### ISSUE TITLE
[ethicapp-v2] No se está mostrando el documento de caso en la pantalla del alumno

### ISSUE THREAD

**Issue by mabarraza** [EthicApp-Development/ethicapp-main#227]
# Descripción del error/bug

Al realizar una actividad como alumno, cuando visualizan las preguntas no se adjunta junto a ellas el documento del caso afectando gravemente la cálidad de la evaluación.

# Detalles
## ¿Cuándo ocurrió?

08-09-2023, durante testeo de la plataforma

## ¿En qué dispositivo fue?

Asus zenbook 14 del mantenedor

## ¿En qué explorador web ocurrió?

Brave [Version 1.57.62 Chromium: 116.0.5845.180 (Official Build) (64-bit)](https://brave.com/latest/)

## ¿Cómo reproducir el error?

Iniciar una actividad como profesor habiendo cargado un documento de caso en ella y luego ingresar a dicha actividad como alumno.

## Detalles adicionales

<img width="676" alt="err_4" src="https://github.com/EthicApp-Development/ethicapp-main/assets/62113405/496d1655-ccab-44ec-88ac-e15ab27923ed">

**Comment by javiersoto99** [comment]
Estoy debugeando el proceso de mostrar el archivo y actualmente se está llamando al endpoint `get-documents` desde la vista del alumno y siempre me está retornando un arreglo vacío (y la actividad tiene archivos cargados):
![image](https://github.com/EthicApp-Development/ethicapp-main/assets/62267638/33cb4aa6-df63-4fc9-8210-dc86a8923570)

**Comment by mabarraza** [comment]
Habrá que revisar que hace con el documento la vista del profesor entonces, porque la llamada de está haciendo pero no encuentra el archivo.

**Comment by mabarraza** [comment]
Creo ya encontré el error o parte de el, por lo que veo el documento se está guardando en la tabla "designs_documents"  mientras que por otro lado a la hora de pedir el documento en la llamada alumno  se llama a la tabla "documents" adjunto fotos, @claudio-alvarez sabes tu cual de las dos tablas hay que usar? También aviso que la tabla de designs_documents no tiene el atributo "title" que se usa en la pantalla alumno para mostrar el doc.

![image](https://github.com/EthicApp-Development/ethicapp-main/assets/62113405/99d0bb0d-892a-42c8-899e-cdf8966dfee2)

![image](https://github.com/EthicApp-Development/ethicapp-main/assets/62113405/4746cc6b-8f3b-4e4d-9485-bb09344bb773)

**Comment by mabarraza** [comment]
Revisando la tabla documents puedo confirmar que en esta no se están guardando los archivos tampoco solo es creada en el seed al iniciar la bdd.

**Comment by mabarraza** [comment]
Resuelto en PR #238
