### ISSUE TITLE
[ethicapp-v2] Fallas en interfaz del alumno para actividad de ordenamiento

### ISSUE THREAD

**Issue by javiersoto99** [EthicApp-Development/ethicapp-main#235]
# Descripción del error/bug
Al iniciar una actividad de ordenamiento en la vista del alumno no se tiene la opción de justificar rol o posición de acorde al diseño del profesor, junto con errores de validación.

# Detalles
## ¿Cuándo ocurrió?
El sábado corriendo un flujo normal de actividad de ordenamiento.

## ¿En qué dispositivo fue?
En mi computador Dell G7.

## ¿En qué explorador web ocurrió?
Google Chrome.

## ¿Cómo reproducir el error?
Correr una actividad de ordenamiento normal.

**Comment by mabarraza** [comment]
Resuelto en PR #238
