### ISSUE TITLE
[ethicapp-v2] Carga de archivo en diseño nuevo se cae si el tamaño del archivo es muy grande

### ISSUE THREAD

**Issue by mabarraza** [EthicApp-Development/ethicapp-main#243]
# Descripción del error/bug
Al cargar un archivo en un nuevo diseño de actividad, si el tamaño de este es muy grande, el botón de carga de archivos se queda esperando por siempre y no deja cargar otro archivo. Por un lado hay que manejar este error cosa de que si llega a ocurrir el caso, se le permita al profesor cargar otro archivo. Por otro hay que enviarle al usuario una notificación comentandole que el tamaño del archivo es muy grande.

# Detalles
## ¿Cuándo ocurrió?
16/09/2023

## ¿En qué dispositivo fue?
Asus Zenbook del mantenedor

## ¿En qué explorador web ocurrió?
Brave

## ¿Cómo reproducir el error?
crear una actividad nueva y agregar un archivo, si nunca termina de cargar revisar el inspect para ver el error correspondiente.

## Detalles adicionales

![image](https://github.com/EthicApp-Development/ethicapp-main/assets/62113405/ddd2bfca-4f18-4d6e-91ee-6d195ef01576)

![image](https://github.com/EthicApp-Development/ethicapp-main/assets/62113405/175a3fd5-1a3a-4fdd-b6fe-7dd14169da0b)

**Comment by javiersoto99** [comment]
Para tener una buena validación, cual debe ser el tamaño máximo para el archivo?

**Comment by claudio-alvarez** [comment]
Lo dejaría en 20 megas, y esto en realidad es un parámetro que se debe configurar en el servidor web (nginx).
________________________________

**Comment by javiersoto99** [comment]
Perfect, de todas formas pude validar por frontend para que no envié un documento de tamaño mayor a 20mb.

**Comment by mabarraza** [comment]
El problema ha sido controlado por front, sin embargo, falta la configuración correspondiente en el backend.
