### ISSUE TITLE
[ethicapp-v2] Falla validación de largo de respuesta en interfaz de alumno

### ISSUE THREAD

**Issue by claudio-alvarez** [EthicApp-Development/ethicapp-main#25]
Commit: f7de468dacb64689446994a82ada0c6a0f007aab
Branch: ethicapp-unstable

En la interfaz del alumno la validación de la respuesta escrita falla. Pasos para reproducir el problema:

- Se envía una respuesta con texto no vacío al servidor, presionando el botón de avión (enviar)
- Se borra el texto de la respuesta. 
- Botón enviar se activa. 
- Al presionar el botón enviar, la respuesta es enviada. No aparece mensaje de error.

Además, cuando hay un mínimo de palabras definido para la respuesta, es posible enviar una respuesta con largo menor al largo mínimo.

**Comment by mabarraza** [comment]
En base a los testeos que he realizado no me  he encontrado con el problema principal que aquí se menciona.
Sin embargo respecto al tema del mínimo de palabras sí se menciona en el issue #204 y se abordará ahí debido a que el resto del contenido de este issue ya no aplica y por tanto será cerrado.
