### ISSUE TITLE
[ethicapp-v2] Elementos duplicados tras merge rama frontend_controllers_refactoring

### ISSUE THREAD

**Issue by mabarraza** [EthicApp-Development/ethicapp-main#252]
# Descripción del error/bug
Luego de haberse realizado el merge de las ramas mencionadas is bien la aplicación no se caía ni nada por el estilo se encontraron múltiples instancias donde había código HTML duplicado.

# Detalles
## ¿Cuándo ocurrió?
Luego del merge a la rama principal el pasado martes 03 de octubre en la noche.

## ¿En qué dispositivo fue?
Computador desarrollador frontend @javiersoto99 

## ¿En qué explorador web ocurrió?
Google Chrome

## ¿Cómo reproducir el error?
Basta con revisar staging de ethicapp (https://alpha.ethicapp.info/login) e ir revisando las diferentes vistas para encontrar alguna con el HTML duplicado.

**Comment by mabarraza** [comment]
@javiersoto99 si tienes algunas fotos de los errores encontrados porfavor agregarlos en comentarios de este Issue.

**Comment by javiersoto99** [comment]
Dentro de los errores de la rama estaba duplicado el html por parte del alumno, no tengo evidencia actualmente en mi rama ya que fue arreglado. También había una pagina que utilizaban lang en vez de translate y sin controlador asociado (forgot-pass.ejs):

![image](https://github.com/EthicApp-Development/ethicapp-main/assets/62267638/ebda7d45-51c5-4088-a263-a0cda82c01fe)

No he notado mayores errores además de la duplicación de html y el forgot-pass.ejs.
