### ISSUE TITLE
[admin-panel] Rechazar e Ignorar solicitudes de cuenta de profesor

### ISSUE THREAD

**Issue by vicentegana10** [EthicApp-Development/ethicapp-main#272]
# Descripción general
Funcionalidad a los botones de ignorar y rechazar una solicitud de cuenta de profesor.

# ¿Cuándo se usaría?
En la vista de la solicitud en especifico cuando se quiera:
a) Ignorar una solicitud tipo spam.
b) Rechazar una solicitud con una razón a ingresar.

**Comment by mabarraza** [comment]
Resuelto en PR #273
