### ISSUE TITLE
[ethicapp-v2] Funcionalidad Export Answer.csv rota

### ISSUE THREAD

**Issue by mabarraza** [EthicApp-Development/ethicapp-main#276]
# Descripción del error/bug
La funcionalidad mencionada no se encuentra activa.

# Detalles
## ¿Cuándo ocurrió?
10/19/2023

## ¿En qué dispositivo fue?
Asus Zenbook

## ¿En qué explorador web ocurrió?
Brave, Chrome

## ¿Cómo reproducir el error?
Revisar alguna actividad finalizada que tenga un mínimo de datos e intentar hacer uso de dicha funcionalidad.

## Detalles adicionales
![image](https://github.com/EthicApp-Development/ethicapp-main/assets/62113405/f5fec106-686b-47de-9d30-08ef093692ef)

**Comment by claudio-alvarez** [comment]
Para comenzar a resolver, sería pertinente determinar si saveCsv es función definida en algún módulo/archivo del proyecto, o si es una dependencia externa.
