### ISSUE TITLE
[ethicapp-v2/api-v2] Proponer metodología de tests de API con ejemplo

### ISSUE THREAD

**Issue by claudio-alvarez** [EthicApp-Development/ethicapp-main#313]
# Descripción general
Nos interesa que la nueva API que nos encontramos desarrollando sea testeable. Para esto, cabe investigar qué herramientas de testeo automático serían convenientes, y en lo posible proporcionar un ejemplo implementado contra alguno de los modelos ya existentes en la API para las operaciones CRUD.

# ¿Cuándo se usaría?
Se usaría constantemente en el desarrollo, como una práctica para asegurar la calidad de la implementación.

**Comment by benjamin-gonzalez-diaz** [comment]
Generé un documento llamado TESTING.md, que tiene la documentación sobre la metodología de testing, usando jest.

**Comment by claudio-alvarez** [comment]
Aprobada la primera versión del documento. Cerramos el issue.
