### ISSUE TITLE
[api-v2] Tests para funciones de registro y autenticación con token

### ISSUE THREAD

**Issue by claudio-alvarez** [EthicApp-Development/ethicapp-main#321]
# Descripción general
Necesitamos desarrollar tests para validar las funciones de registro de usuario y autenticación con token. Serían dos tests basados en Jest, según lo documentado en TESTING.md: test para registro de usuario, y test para autenticación de usuario.

Hay ciertas reglas respecto al _registro de usuario_ que tendrían que ser consideradas, y con base a ello ciertas funcionalidades que tendrían que ser completadas.

- El registro de usuario requiere que el endpoint pueda recibir la contraseña y la confirmación de contraseña (password y password_confirmation).
- Deberíamos validar que el largo mínimo de contraseña sea de ocho caracteres.

Luego, respecto a la autenticación, probar:

- Usuario no existente
- Usuario existente con contraseña inválida, y contraseña válida

# ¿Cuándo se usaría?
Es fundamental incorporar tests para verificar que funciones de registro y autenticación de usuarios estén, completas, consistentes y correctamente operativas.

**Comment by claudio-alvarez** [comment]
Esto ya está funcional y pasa los tests, ¿es así @benjamin-gonzalez-diaz?

**Comment by benjamin-gonzalez-diaz** [comment]
si esta bien y se probo por medio de los test,
