### ISSUE TITLE
[api-v2] Tests para creación de sesión de EthicApp e incorporación de usuarios a la sesión

### ISSUE THREAD

**Issue by claudio-alvarez** [EthicApp-Development/ethicapp-main#322]
# Descripción general
Necesitamos tests para verificar la funcionalidad de creación de sesión e incorporación de usuarios a sesión de trabajo. Sobre esto, algunas precisiones de la funcionalidad:

- Creación de sesión implica que se genera un código aleatorio que debe ser distribuido a los usuarios. El código debe tener un largo de 6 caracteres hexadecimales. Se puede investigar cómo lo hace la implementación legada de esta funcionalidad y replicarlo en la nueva implementación.
- El endpoint de creación se sesión puede retornar el código de la sesión generada en un objeto descriptor de sesión. Podría contener campos id (id de la sesión) code (código de acceso) y status (open).

El test de creación de sesión debe consistir en:

- Repetir 10 veces la operación de creación de sesión.
- Verificar que todos los códigos de sesión creados sean distintos.

Luego, necesitamos que el usuario se pueda incorporar a una sesión creada, para esto, el endpoint podría ser:
POST /api-v2/sessions/users

El request tendría que pasar un objeto que incluya el código de la sesión a la cual unirse (code), junto con el id del usuario (user_id).

Para probar la incorporación de usuario a sesión, considerar:

- Usuario tiene que estar autenticado (token válido).
- ID de usuario (user_id) puede ser existente o inexistente (error).
- Código de sesión (code) puede ser existente o inexistente (error).

La verificación completa terminaría por realizar la siguiente petición:

GET /api-v2/sessions/:id/users

Tendría que retornar una objeto que contenga los IDs de todos los usuarios en la sesión con :id, y el usuario incorporado a la sesión en el test tendría que aparecer en la lista.

# ¿Por qué es necesario?
A fin de verificar las funciones que permiten crear e ingresar a sesión de trabajo en EthicApp.

**Comment by claudio-alvarez** [comment]
Veo que esto está implementado y pasa los tests, favor confirmar @benjamin-gonzalez-diaz.

**Comment by benjamin-gonzalez-diaz** [comment]
si esta bien, se probo en los test de sessionUser.test.js,
