### ISSUE TITLE
[ethicapp-v2] Aumentar separación entre enunciado de pregunta y escala de diferencial semántico

### ISSUE THREAD

**Issue by claudio-alvarez** [EthicApp-Development/ethicapp-main#33]
# Descripción general 
Se debe aumentar a 1em el espacio entre el texto de la pregunta y la escala de diferencial semántico en la interfaz de respuesta del alumno.

# ¿Cuándo se usaría?
En la vista de alumno al responder este tipo de preguntas.

# Más información
![1215c17c-ab9a-4189-9465-1c3dd209ba0f](https://user-images.githubusercontent.com/752908/167220216-3ad797fb-e534-4061-86f0-773695a2de49.jpg)

**Comment by mabarraza** [comment]
Si bien no fue referenciado en ningún PR en particular a dia de hoy este issue se encuentra resuelto como se muestra en la siguiente foto:
<img width="818" alt="issue-33" src="https://github.com/EthicApp-Development/ethicapp-main/assets/62113405/000de96e-30ba-4a74-91e9-bfc9f0b5fa77">
