### ISSUE TITLE
[ethicapp-v2] Diseño de actividades: documentos relativos a fases

### ISSUE THREAD

**Issue by ifgarces** [EthicApp-Development/ethicapp-main#70]
# Descripción general
Como mencionó [Claudio](https://github.com/EthicApp-Development/ethicapp-main/issues/66#issuecomment-1327589652) en #66, actualmente el documento adjunto es único y relativo a un diseño. Se quiere la posibilidad de adjuntar un documento a cada fase.

# ¿Cuándo se usaría?
Actividades con más de un caso o documento adjunto, evitando tener que crear otra actividad para otro documento.

**Comment by claudio-alvarez** [comment]
Estamos desarrollando nueva funcionalidad de casos en el período segundo semestre 2024. En función de esto, veremos cómo conectar los casos con las fases de los diseños.
